spring:
  application:
    name: ciudad-services
  datasource:
    username: root
    password: ""
    url: jdbc:mysql://localhost:3306/ciudad?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081